### ISSUE TITLE
The `port` option in `.bedeckedrc` is ignored

### ISSUE THREAD

**Issue by lily-pytel** [jtrussell/bedecked#24]
Example .bedeckedrc file: 
```
{
	"optHistory": true,
	"theme": "moon",
	"port": 999
}
```

When running `bedecked --server index.md`, the port used is the default `9090`

**Comment by jtrussell** [comment]
Hmmm yeah I guess none of the cli-specific options are supported by `.bedeckedrc`. Probably should be.
